### ISSUE TITLE
Feature Request: Add a static for transitioning to new page

### ISSUE THREAD

**Issue by motleydev** [kriasoft/react-app#1]
Instead of requiring an onClick event to navigate pages, it'd be nice to have a static available such as Link.to(path) to call after a complex process.

**Comment by koistya** [comment]
@motleydev have you check the [`Link`](https://github.com/kriasoft/react-app/blob/master/src/Link.js) component? E.g. `import { Link } from 'react-app'; <Link to="/hello">Hello</Link>`

**Comment by koistya** [comment]
Something like this?

```js
import { history } from 'react-app';
history.push(path);
```

**Comment by motleydev** [comment]
`history.push` would be awesome! That's exactly what I'm thinking. The other possibility would be to have a callback to Link that you could define a function that get's called before the history stuff takes place. I'm essentially trying to set a global lang param on my redux store that then dictates how the page get's reloaded.

**Comment by koistya** [comment]
I have temporarily removed the runtime components, will bring them back in the next version.
