### ISSUE TITLE
Project name inconsistancy

### ISSUE THREAD

**Issue by TheoMer** [kriasoft/react-app#12]
Here the project s known as 

> react-app

 but over on npm, https://www.npmjs.com/package/react-app-tools, it is known as 

> react-app-tools

You might wish to amend this.

**Comment by koistya** [comment]
Yep, need to update `tools/README.md` to highlight what the difference between these to and avoid confusion.

**Comment by TheoMer** [comment]
Ah, ok. In which case it would be more than a simple project name change. At the moment to initiate a new project one does, `react-app new` for both.
