### ISSUE TITLE
Error: Cannot find module 'react-app-tools/run'

### ISSUE THREAD

**Issue by drejohnson** [kriasoft/react-app#13]
Followed docs but when running ```react-app run``` I get: ```Error: Cannot find module 'react-app-tools/run'```

**Comment by koistya** [comment]
Can you check please if there is folder `node_modules/react-app-tools` in you project?

**Comment by drejohnson** [comment]
Yes, there is a ```node_modules/react-app-tools``` folder. Inspecting it's ```package.json``` file, I see ```"raw": "react-app-tools@^0.2.0"```

**Comment by monahxxx** [comment]
npm start works for me
