### ISSUE TITLE
React-app SDK v1.1.1 update fails

### ISSUE THREAD

**Issue by TheoMer** [kriasoft/react-app#16]
OS: Windows 10 Pro
Node: version 6.2.2
NPM: version 3.9.5

Steps
1. ncu
2. ncu -a
3. npm install
4. npm start

See attached image:

![update-error](https://cloud.githubusercontent.com/assets/15969262/17200915/3b3581d2-5481-11e6-8b25-d230ac412839.jpg)

**Comment by TheoMer** [comment]
Ok, so the above mentioned error message was due to me not reading instructions fully. but my output now looks as follows:

![update-error2](https://cloud.githubusercontent.com/assets/15969262/17201264/d0fb188c-5484-11e6-8769-76387d2165e6.jpg)

**Comment by TheoMer** [comment]
By 

> Rename page field of each route in routes.json file with component

I take it that you meant

> "page": "./routes/home"

and not

> "component": "./routes/home"

correct?

**Comment by koistya** [comment]
@TheoMer Thanks for the heads up, much appreciated! I have updated the [release notes](https://github.com/kriasoft/react-app/releases/tag/v1.1.1) to `v1.1.1` that addresses this issue.
