### ISSUE TITLE
No package.json created

### ISSUE THREAD

**Issue by spdaly** [kriasoft/react-app#9]
I just installed the tool and created my first project. 

```
$ react-app new
Scaffolding a new JavaScript application project.
Installing npm modules. This may take a couple minutes.

npm WARN enoent ENOENT: no such file or directory, open '/Users/steve/Projects/package.json'
npm WARN Projects No description
npm WARN Projects No repository field.
npm WARN Projects No README data
npm WARN Projects No license field.

All done! Now you can launch your app by running: npm start

$ ls
components core       pages      public     test       utils

$
```

**Comment by antoinerey** [comment]
Yep, same as @spdaly.

I'm using :
- node v6.2.2
- npm v3.9.5

**Comment by TheoMer** [comment]
OS: Windows 10 Pro
node: version 6.2.2
npm: version 3.9.5

I'm experiencing exactly the same as has been mentioned here. See image below:

![package-error](https://cloud.githubusercontent.com/assets/15969262/17159270/ee83b752-5393-11e6-85ef-47ba65752331.jpg)

**Comment by koistya** [comment]
[![image](https://cloud.githubusercontent.com/assets/197134/17168697/78fb4a78-53ec-11e6-81c0-cb65348b852b.png)](https://twitter.com/ReactSDK/status/758215587600490496)
